# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
    knp_menu.renderer.twig.options:
        allow_safe_labels: true
        currentClass: active
        ancestorClass: active open
        lastClass: last-child
        branch_class: dropdown

services:
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]
    gedmo.listener.softdeleteable:
        class:        Gedmo\SoftDeleteable\SoftDeleteableListener
    twig.extension.intl:
        class: Twig_Extensions_Extension_Intl
        tags:
            - { name: twig.extension }
    twig.extension.utilextension:
        class: Cangulo\UtilBundle\Twig\UtilExtension
        arguments: ['@service_container']
        autowire: true
        tags:
            - { name: twig.extension }
    security.login_na_tora:
        class: Cangulo\SecurityBundle\Security\LoginNaTora
        autowire: true
    util.data_service:
        class: Cangulo\UtilBundle\Data\Service
        autowire: true
    util.initialization_subscriber:
        class: Cangulo\UtilBundle\EventSubscriber\InitializationSubscriber
        autowire: true
        tags:
            - { name: kernel.event_subscriber }